### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef

### teszt
get {{host}}/api/

### get
get {{host}}/api/instruments


### get products by id
get {{host}}/api/instruments/3

### post 
POST  {{host}}/api/instruments
Accept: application/json
Content-Type: application/json
 
{
    "name": "Karamel",
    "description": "Kézzel termelt folyás",
    "brand": "farkkas",
    "price": 8012400,
    "quantity": 50023
}

### delete

DELETE {{host}}/api/instruments/14
Accept: application/json
Content-Type: application/json

### patch
PATCH {{host}}/api/instruments/9
Accept: application/json
Content-Type: application/json
 
{
    "price": 1,
    "quantity": 2
}